### ISSUE TITLE
Move zip to /publish directory

### ISSUE THREAD

**Issue by vickyRathee** [jogoussard/node-repack-zip#10]
Hi @jogoussard ,

Anyway in node-repack-zip to give directory option for zip? 
For example, I want to put the projectName.zip on the `/publish` directory, instead the project root directory when all done.

**Comment by jogoussard** [comment]
Hi @vickyrathee - the complete command is `repack-zip [source] [destination]` so you should be able to make that work by providing the current working dir as source and the `publish` folder location as destination. Let me know how it goes.

**Comment by vickyRathee** [comment]
@jogoussard  I am getting error

![image](https://user-images.githubusercontent.com/6106479/100717354-eead7200-33df-11eb-821a-db9b64bbe5b6.png)

**Comment by jogoussard** [comment]
Looks like it could not open your publish directory - I guess this directory is created prior to calling the script? If yes, I'll try to reproduce.

**Comment by vickyRathee** [comment]
Yes, the directory was always there (I don't want repack to create it) as you can see on the left navigation view.

I think the best way will be to check if destination directory exits, and create if not.

```
fs.access(destDir, function(err) {
  if (err && err.code === 'ENOENT') {
    fs.mkdir(myDir); //Create dir in case not found
  }
});
```

**Comment by jogoussard** [comment]
Ah - my bad.
The issue is here:
```
function pack({ source, destination }) {
    let files = getGlobPatterns({ cwd: source })
        .then(getFiles({ cwd: source }));

    let outputFilename = destination
        ? Promise.resolve(destination)
        : getDefaultOuputFilename({ cwd: source })
```
`destination` is a file not a dir - so use
`repack-zip . publish/lambda.zip`

**Comment by vickyRathee** [comment]
yes, working now.
