### ISSUE TITLE
additional include patterns

### ISSUE THREAD

**Issue by Enalmada** [jogoussard/node-repack-zip#3]
Next.js needs the top level .next directory to be in the zip but it seems like **/* is not including it because of the leading dot.  Could you explicitly add hidden files and directories?

**Comment by Enalmada** [comment]
Actually my situation is a bit worse than I initially thought....  

I am trying to use reason-react with next.js deployed to amazon and there is more than just hidden files/directories I need.  I need some .ebextensions, node_modules/.bin, node_modules/bs-platform/lib/js, lib/bs.
I am working around that right now by adding them in after repack-zip:
`
    "build": "next build && repack-zip && zip -qr -b . with-reasonml.zip .next .ebextensions node_modules/.bin node_modules/bs-platform/lib/js lib/bs .babelrc .merlin ",
`

So to be generic for everyone, it would be nice if node-repack-zip allowed me to add additional include patterns to avoid the manual step to a .packinclude file.

repack-zip makes such a huge difference!  Thanks for the excellent community contribution.

**Comment by jogoussard** [comment]
I know I'm very late - I added a 'repackZipConfig' support in package.json that allows includes/excludes glob patterns to be specified.
